### PR TITLE
Update to changes in hpp-fcl.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
Follows https://github.com/humanoid-path-planner/hpp-fcl/pull/103

**Comment by stonneau** [comment]
Thanks @jmirabel . We'll review this next week if this is not urgent

**Comment by jmirabel** [comment]
It isn't.

**Comment by jmirabel** [comment]
@nim65s you'll need this too.

**Comment by nim65s** [comment]
Thanks !

**Pull request merged**
