### PR TITLE
Format

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

This PR reformat the code, as some parts where not correctly building in the binary release:

In Python:
- remove useless imports
- avoid `*` imports
- ignore `script`, `profile` and `affordance-tests` folders for linters (I stopped trying to fix those when the diff reached 100 000 lines… Maybe this is a bit insane.)
- fix spaces around operators, at the beginning of comments, before function calls, in function arguments declaration, at end of lines
- ensure that the print statement is correctly used and imported (as long as we want to comply with Python 2)
- changes a few `x == None` into `x is None`
- remove some useless parenthesis in conditions
- avoid lines longer than 120 columns

In C++:
- just use clang-format

There is still some work left:
- according to the CI:
```
./src/hpp/corbaserver/rbprm/rbprmstate.py:104:109: F821 undefined name 'stateId'
./src/hpp/corbaserver/rbprm/rbprmstate.py:114:109: F821 undefined name 'stateId'
./src/hpp/corbaserver/rbprm/rbprmfullbody.py:360:5: F811 redefinition of unused 'createState' from line 251
```
- The documentation in written in comments. In Python, we should use [docstring](https://www.python.org/dev/peps/pep-0257/)
- ~60k lines of code are not checked

### CODE REVIEW

**Comment by jmirabel** [comment]
> The documentation in written in comments. In Python, we should use [docstring](https://www.python.org/dev/peps/pep-0257/)

It may be for Doxygen compatibility. I don't think Doxygen reads docstrings.

**Comment by nim65s** [comment]
In this case, shouldn't I see anything with `make doc` ?

**Comment by nim65s** [comment]
Hum, in the file list of the HTML doc generated by Doxygen, I can see one python file, but almost nothing inside

**Comment by jmirabel** [comment]
It was a shot in the dark. I don't know whether the Python files ought to be parsed by Doxygen. At least, it is the case in hpp-corbaserver and hpp-rbprm-corba.

**Pull request merged**
