### PR TITLE
Update to changes in hpp-corbaserver. 

### PR DESCRIPTION
**Pull request by jmirabel**
Needs humanoid-path-planner/hpp-corbaserver#73

I don't know how to test those changes. Is there a script which should work out-of-the-box from an installation from the Makefile ?

### CODE REVIEW

**Comment by jmirabel** [comment]
I validated it by creating instance of Python class hpp.corbaserver.rbprm.client.Client.
Given the changes I propose, I think there shouldn't be any problem with user scripts.

**Comment by stonneau** [comment]
I ll test it tomorrow, thanks

**Comment by stonneau** [comment]
ps: for future test, the darpa hyq scenario should always work:

./run.sh hpp-rbprm-corba/script/scenarios/demos/darpa_hyq.py

**Comment by jmirabel** [comment]
I had a look at the Readme and found the script you mention. Where is `./run.sh` ? Is it the one in `hpp-rbprm-corba/script/scenarios/demos/`. If yes, then it is broken (gepetto-viewer-server executable disappeared).

**Comment by stonneau** [comment]
yes it was the one. Thanks for updating it. This should have been raised by the integration server... weird

**Pull request merged**
