### PR TITLE
Remove rbprm.ProblemSolver python class

### PR DESCRIPTION
**Pull request by pFernbach**
And use the same class as hpp-corbaserver.

This required some changes in the other python classes and introduce an API change in ptyhon : 

All calls to `foo.client.basic` are replaced by `foo.client` and `foo.client.rbprm` by `foo.clientRbprm`.

### CODE REVIEW

**Comment by jmirabel** [comment]
For your information, you can now inherits from hpp.corbaserver.ProblemSolver. This allows to remove all functions that are like:
```python
    def function (self, args):
        return self.client.basic.robot.function (args)
```

**Comment by pFernbach** [comment]
> For your information, you can now inherits from hpp.corbaserver.ProblemSolver. 

Thanks for the info, I think I tried few years ago and there was some issues.

**Comment by jmirabel** [comment]
> > For your information, you can now inherits from hpp.corbaserver.ProblemSolver.
> 
> Thanks for the info, I think I tried few years ago and there was some issues.

I

**Comment by jmirabel** [comment]
Sorry for the wrong manipulation.

-1000 lines: that's a nice simplification !

**Comment by pFernbach** [comment]
> Sorry for the wrong manipulation.
> 
> -1000 lines: that's a nice simplification !

The whole hpp.corbaserver.robot.py file was nearly copied twice ...

**Comment by pFernbach** [comment]
I'll rebase this branch on the current devel branch for easier merge.

**Pull request closed without merging**
